// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cars.sql

package database

import (
	"context"
)

const createCar = `-- name: CreateCar :one
INSERT INTO cars (
    state, city, year, make, model, drive, vin, color, miles, price, msrp
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING state, city, year, make, model, drive, vin, color, miles, price, msrp
`

type CreateCarParams struct {
	State string
	City  string
	Year  string
	Make  string
	Model string
	Drive string
	Vin   string
	Color string
	Miles int32
	Price int32
	Msrp  int32
}

func (q *Queries) CreateCar(ctx context.Context, arg CreateCarParams) (Car, error) {
	row := q.db.QueryRowContext(ctx, createCar,
		arg.State,
		arg.City,
		arg.Year,
		arg.Make,
		arg.Model,
		arg.Drive,
		arg.Vin,
		arg.Color,
		arg.Miles,
		arg.Price,
		arg.Msrp,
	)
	var i Car
	err := row.Scan(
		&i.State,
		&i.City,
		&i.Year,
		&i.Make,
		&i.Model,
		&i.Drive,
		&i.Vin,
		&i.Color,
		&i.Miles,
		&i.Price,
		&i.Msrp,
	)
	return i, err
}
