// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: city_auction_map.sql

package database

import (
	"context"
)

const checkAuctionExists = `-- name: CheckAuctionExists :one
SELECT EXISTS(SELECT 1 FROM city_auction_map WHERE state_code = $1 AND city = $2)
`

type CheckAuctionExistsParams struct {
	StateCode string
	City      string
}

func (q *Queries) CheckAuctionExists(ctx context.Context, arg CheckAuctionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkAuctionExists, arg.StateCode, arg.City)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAuction = `-- name: GetAuction :one
SELECT auction_name 
FROM city_auction_map 
WHERE state_code = $1 AND city = $2
`

type GetAuctionParams struct {
	StateCode string
	City      string
}

func (q *Queries) GetAuction(ctx context.Context, arg GetAuctionParams) (string, error) {
	row := q.db.QueryRow(ctx, getAuction, arg.StateCode, arg.City)
	var auction_name string
	err := row.Scan(&auction_name)
	return auction_name, err
}
