// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Car struct {
	State string
	City  string
	Year  string
	Make  string
	Model string
	Drive string
	Vin   string
	Color string
	Miles int32
	Price int32
	Msrp  int32
}
