// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Car struct {
	State  string
	City   string
	Year   string
	Make   string
	Model  string
	Trim   string
	Drive  string
	Vin    string
	Color  string
	Miles  int32
	Price  int32
	Msrp   int32
	Notes1 *string
	Notes2 *string
}

type CarsStaging struct {
	State  string
	City   string
	Year   string
	Make   string
	Model  string
	Trim   string
	Drive  string
	Vin    string
	Color  string
	Miles  int32
	Price  string
	Msrp   string
	Notes1 *string
	Notes2 *string
}

type Dib struct {
	Vin       string
	Queue     []byte
	UpdatedAt pgtype.Timestamp
}
